### ISSUE TITLE
Tinker's tools correct sounds

### ISSUE THREAD

**Issue by ghost** [makamys/MAtmos#4]
Would it be possible to add these? Or maybe a config file for that?

**Comment by makamys** [comment]
Hm? What do you mean?

**Comment by ghost** [comment]
The mod doesn't recognize tinkers swords for example and does not trigger the blade sound

**Comment by makamys** [comment]
Oh, so it's like the alias system I have for blocks, just for items. I'll consider it, but it won't be high priority since the item sounds aren't the focus of this mod.
As a workaround, you can add Dynamic Surroundings, which has item sounds that work with modded tools. (It doesn't interfere with MAtmos when correctly configured.)
