### ISSUE TITLE
[1.12.2 Mod Incompatibility] Weather, Storms & Tornadoes mod rain sound not playing

### ISSUE THREAD

**Issue by juraj-hrivnak** [makamys/MAtmos#7]
Simply when starts raining using Weather2 sometimes rain sound effect is not playing.
After disabling Matmos with in-game button, Vanilla sound effect works properly.
This issue is not in 1.7.10 (tested)

**Comment by makamys** [comment]
Did you to set `rain.suppress=false` in `userconfig.cfg`? That fixed it for me.

**Comment by juraj-hrivnak** [comment]
Yeah `rain.suppress=false` is working, but It will be nicer overall to have the Matmos sound.
The thing is there is issue with combination of Serene seasons and Weather2. Basically Weather2 make rain sound when is snowing. But when Matmos enabled everything is working except for this issue.
I know it's little out of your scope. If you will have time to look on it, not only I will be pleasured.

**Comment by makamys** [comment]
Alright, so the reason this was happening is that Minecraft says that it's raining when the strength of rain is over 20%. On 1.7.10, Weather2 played along with this and set the rain strength to 30% once it started raining, so everything worked correctly.

On 1.12.2 on the other hand, Weather2 implemented its own way of rendering rain, so it didn't have to play by these rules anymore. It could have 1% rain and still draw a drizzle. But MAtmos wasn't picking up that it was raining when this was happening, because it was under 20%. 

So I added a config option (`rain.strengthThreshold`) that lets you configure the strength threshold above which it's considered to be raining. Setting this to 0% fixes the issue.

**Comment by juraj-hrivnak** [comment]
That's perfect! Thank you very much!
